config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resource :profile, only: [:show], controller: "users/profile"
    resources :teams, controller: "users/teams"
    resources :sports, controller: "users/sports"
  end

  resources :teams, except: [:index, :show, :create, :new, :edit, :destroy, :update] do
    resources :invitations, controller: 'teams/invitations'
  end

  get 'invitations/:authentication_token', to: 'teams/invitations#redeem'

  resources :organizations, only: [:index, :show] do
    resources :teams, only: :index, controller: "organizations/teams"
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :team
  belongs_to :user


  def self.find_for_redemption(token)
    @invitation = self.where(authentication_token: token, authentication_token_redeemed_at: nil).last
  end

  def mark_redeemed!
    self.update(authentication_token_redeemed_at: Date.current, authentication_token: nil)
  end

  def associate_team_and_build_user(team)
    user = self.build_user(email: self.email, name: self.name)
    user.teams << team
    user.save
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :teams
  has_many :users, through: :teams
  has_many :sports, through: :users
end

app/models/sport.rb
class Sport < ApplicationRecord
  CATEGORIES = ['soccer', 'football', 'baseball', 'lacrosse', 'running', 'swimming', 'rowing', 'cycling', 'chess', 'basketball']

  belongs_to :user
  belongs_to :team

  #normalized total hours cache_counter
  after_save :sync_user_hours_cache_counter

  validates :participation_hours, presence: true

  private
    #not a real cache counter, but hack using lifecycle event
    def sync_user_hours_cache_counter
      hours = self.user.sports.sum(:participation_hours)
      self.user.update(total_participation_hours: hours)
    end
end

app/models/team.rb
class Team < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :sports
  has_many :invitations
  belongs_to :organization
end

app/models/user.rb
class User < ApplicationRecord
  enum units_preference: [ :metric, :imperial ]
  #TODO implement unit rendering and selection options

  has_and_belongs_to_many :teams
  has_many :sports

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/organizations/teams_controller.rb
class Organizations::TeamsController < ApplicationController

  def index
    @org = Organization.includes(teams: :users).find(params[:organization_id])
    @teams = @org.teams
    render 'users/teams/index'
  end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.includes(teams: {users: :sports}).find(params[:id])
    @organization_data = OrganizationSportDataService.new(@organization).perform
  end

end

app/controllers/teams/invitations_controller.rb
class Teams::InvitationsController < ApplicationController
  before_filter :find_team, only: [:new, :create]

  def new
    @invitation = @team.invitations.new()
  end

  def create
    #random "enough", maybe check db for uniqueness in V2
    token = SecureRandom.uuid
    @invitation = @team
                    .invitations
                    .build(invitation_params.merge(authentication_token: token))

    @invitation.associate_team_and_build_user(@team)

    @invitation.save #propagates down to user

    InvitationMailer.invitation_email(@team, @invitation).deliver
  end

  def redeem
    @invitation = Invitation.find_for_redemption(params[:authentication_token])
    if !@invitation
      flash[:error] = 'Whoops this link has expired'
      redirect_to root_path
    else
      flash[:success] = 'Welcome! This is your profile page. Add some information!'
      @invitation.mark_redeemed!
      redirect_to user_path(@invitation.user)
    end
  end

  private

    def find_team
      @team = Team.find(params[:team_id])
    end

    def invitation_params
      params.require(:invitation).permit(:email, :name)
    end

end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController


  def show
    @user = User.find(params[:user_id])
    @sport_data = SportDataService.new(@user).perform
    authenticate_and_maybe_redirect
  end

  private
    def authenticate_and_maybe_redirect
      if @user.private_profile?
        flash[:error] = 'This user is private'
        redirect_to root_path
      end
    end
end

app/controllers/users/sports_controller.rb
class Users::SportsController < ApplicationController
  before_action :fetch_user

  def new
    @sport = Sport.new
  end

  def create
    @sport = @user.sports.create(sport_params)
  end

  def update
    @sport = @user.sports.find(params[:id])
    @sport.update(sport_params)
    
    render :create
  end

  def edit
    @sport = @user.sports.find(params[:id])
  end

  private

    def fetch_user
      @user = User.find(params[:user_id])
    end

    def sport_params
      params.require(:sport).permit(:participation_hours, :participation_date, :name, :team_id)
    end
end

app/controllers/users/teams_controller.rb
class Users::TeamsController < ApplicationController
  
  def index
    @user = User.includes(teams: :users).find(params[:user_id])
    @teams = @user.teams
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.includes(:sports).order(:id).all
  end

  def show
    @user = User.includes(sports: :team).find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :height_meters, :weight_kilograms, :private_profile)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def sport_icon(sport_name)
    #TODO real icon sets not remote image hacks :(
    sports = {
      rowing: "https://www.iconshock.com/img_vista/IPHONE/transportation/jpg/row_boat_icon.jpg",
      soccer: "https://image.flaticon.com/icons/svg/53/53283.svg",
      football: "https://www.iconexperience.com/_img/i_collection_png/512x512/plain/football.png",
      baseball: "https://d30y9cdsu7xlg0.cloudfront.net/png/561-200.png",
      lacrosse: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Crossed_lacrosse_sticks.svg/2000px-Crossed_lacrosse_sticks.svg.png",
      running: "https://d30y9cdsu7xlg0.cloudfront.net/png/72758-200.png",
      swimming: "https://image.freepik.com/free-icon/silhouette-of-a-swimming-person-on-a-wave_318-27333.jpg",
      cycling: "https://d30y9cdsu7xlg0.cloudfront.net/png/536-200.png",
      chess: "https://www.iconsfind.com/wp-content/uploads/2015/11/20151106_563c235abcd0c.png",
      basketball: "https://d30y9cdsu7xlg0.cloudfront.net/png/106597-200.png"
    }.with_indifferent_access

    image_tag(sports[sport_name], style: 'width: 15px;height:15px;', data:{toggle:"tooltip", placement: "top", title: sport_name})
  end

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Sporttrack"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'Sport Track', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "All Organizations", organizations_path
       
    .container
      #modal.modal.fade
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
    %footer
      .well
        .container
          %p 
            Lorem Ipsum Sports Track data example

app/views/organizations/index.html.haml
.row
  .col-lg-12
    %ul.list-group
      - @organizations.each do |org|
        %li.list-group-item
          =link_to org.name, organization_path(org)
    =# render partial: 'shared/users/row', locals: {users: @users, full_render: true}

app/views/organizations/show.html.haml
.row
  .col-md-5
    .well
      %h3= @organization.name.titleize
      %p Teams: #{@organization.teams.count}
      %p Users: #{@organization.users.count}

%hr
  #organization-data
    %ul#tabs.nav.nav-tabs{"data-tabs" => "tabs"}
      - @organization_data[:sport_categories].each_with_index do |category, i|
        %li{class: ('active' if i == 0).to_s}
          %a{"data-toggle" => "tab", :href => "##{category}"}= category.titleize

    .tab-content

      - @organization_data[:sport_categories].each_with_index do |category, i|
        .tab-pane{id: "#{category}", class: ('active' if i == 0).to_s}
          %h4= category
          .row
            .col-md-12
              %div.highchart-chart{id:"#{category}-chart", style: 'width:100%;'}
              .data{data: {hours: @organization_data[:participation_data][category].to_json} }
.row
  .col-md-12
    %hr
      #user-teams-container
        = link_to 'See All Teams', organization_teams_path(@organization), remote: true, class: 'btn btn-primary'

app/views/shared/sports/_index.html.haml
= "(#{@user.total_participation_hours} hours total)"
- @user.sports.each do |sport|
  %li.list-group-item
    = link_to edit_user_sport_path(@user, sport), remote: true do
      %i.fa.fa-pencil
    = sport.participation_date
    = sport_icon(sport.name)
    #{sport.name.titleize}
    \- #{sport.team.name}
    \- #{sport.participation_hours} #{'hours'.pluralize(sport.participation_hours)}

app/views/shared/users/_row.html.haml
.main-box.clearfix
  .main-box-body.clearfix
    .table-responsive
      %table.table.user-list
        %thead
          %tr
            %th
              %span User

            %th
              %span Total Hours

            - if full_render
              %th
                %span Sports

            %th
              %span Email

        %tbody
          - users.each do |user|
            %tr{class: ('active' if user == @user)}

              %td
                %img{alt: "", src: "https://maxcdn.icons8.com/Share/icon/Users//user1600.png", style: 'max-width:50px'}
                = link_to user.name, user_path(user), class: 'user-link'
                %span.user-subhead
                Joined #{l( user.created_at, format: :short)}

              %td.text-center
                = user.total_participation_hours

              - if full_render
                %td.text-center
                  - user.sports.pluck(:name).uniq.each do |sport_name|
                    = sport_icon(sport_name)

              %td
                = mail_to user.email

app/views/users/_edit.html.haml
= form_for @user, url: user_path(@user), method: :put, remote: true do |f|
  .form-group
    .row
      .col-md-6
        %label Name
        = f.text_field :name, class: 'form-control'
      .col-md-6
        %label Email
        = f.text_field :email, class: 'form-control'
  .form-group
    .row
      .col-md-6
        %label Height (m)
        = f.number_field :height_meters, step: "any", class: 'form-control'
      .col-md-6
        %label Weight (kg)
        = f.number_field :weight_kilograms, step: "any", class: 'form-control'
  .form-group
    .row
      .col-md-12
        %label 
          =f.hidden_field :private_profile, value: true
          = f.check_box :private_profile
          Private Profile?
  .form-group
    .row
      .col-md-12
        = f.submit 'Save',  class: 'btn btn-primary btn-sm'

app/views/users/_personal_profile.html.haml
.well.well-sm
  .row
    .col-sm-6.col-md-4
      %img.img-rounded.img-responsive{:alt => "", :src => "https://maxcdn.icons8.com/Share/icon/Users//user1600.png"}/
    .col-sm-6.col-md-8
      %h4= @user.name
      %p
        %i.fa.fa-envelope
        = @user.email
      %p
        %i.fa.fa-tag
          = @user.height_meters
        m
        |
        %i.fa.fa-balance-scale
          = @user.weight_kilograms
          kg
      .btn-group
        // maybe refactor into a view helper if complexity grows

        = link_to user_profile_path(@user), class: "button btn btn-primary #{'disabled' if @user.private_profile?}" do
          %i.fa.fa-globe
          = @user.private_profile? ? 'Profile is private' : "Public Page"
      .pull-right
        =link_to 'edit', edit_user_path(@user), remote: true

app/views/users/edit.js.erb
$('#user-edit').html("<%= j(render partial: 'edit') %>")

app/views/users/index.html.haml
.row
  .col-lg-12
    = render partial: 'shared/users/row', locals: {users: @users, full_render: true}

app/views/users/profile/show.html.haml
.row
  .col-md-6
    .well.well-sm
      .row
        .col-sm-6.col-md-4
          %img.img-rounded.img-responsive{:alt => "", :src => "https://maxcdn.icons8.com/Share/icon/Users//user1600.png"}/
        .col-sm-6.col-md-8
          %h4= @user.name
          %p
            %i.fa.fa-envelope
            = @user.email
          %p
            %i.fa.fa-tag
              = @user.height_meters
            m
            |
            %i.fa.fa-balance-scale
              = @user.weight_kilograms
              kg
.row
  .col-md-12
    #chart


:javascript
  Highcharts.chart('chart', {
      chart: {
          type: 'column'
      },
      title: {
          text: 'Sport Participation'
      },
      xAxis: {
          categories: #{@sport_data[:last_weeks_dates]},
          crosshair: true
      },
      yAxis: {
          min: 0,
          title: {
              text: 'Sports (hours)'
          }
      },
      tooltip: {
          headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
          pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
              '<td style="padding:0"><b>{point.y:.1f} hours</b></td></tr>',
          footerFormat: '</table>',
          shared: true,
          useHTML: true
      },
      plotOptions: {
          column: {
              pointPadding: 0.2,
              borderWidth: 0
          }
      },
      series: #{@sport_data[:data].to_json}
  });

app/views/users/show.html.haml
.container
  .row
    .col-md-5
      #user-personal-profile
        = render 'personal_profile'
    .col-md-7
      #user-edit
  .row
    .col-sm-12
      %ul#tabs.nav.nav-tabs{"data-tabs" => "tabs"}
        %li.active
          %a{"data-toggle" => "tab", :href => "#sports"} Sports
        %li
          %a{"data-toggle" => "tab", :href => "#teams"} Teams
      .tab-content
        #sports.tab-pane.active
          %h4 All Sports Events
          .pull-right
            =link_to "add new sport", new_user_sport_path(@user), remote: true
          %ul.list-group
            #user-sports
              = render partial: 'shared/sports/index'
        #teams.tab-pane
          %br
          #user-teams-container
            = link_to 'See All Teams', user_teams_path(@user), remote: true, class: 'btn btn-primary'
         

app/views/users/sports/_edit.html.haml
.modal-dialog
  .modal-content
    .modal-header
      Add New Sports Event
    = form_for @sport, url: user_sport_path(@user, @sport), method: :put, remote: true do |f|
      = render partial: 'form', locals: {f: f}

app/views/users/sports/_form.html.haml
.modal-body
  .row
    .col-md-6
      %label Sport Category
      = f.select :name, options_for_select( Sport::CATEGORIES, @sport.name), {}, class: 'form-control'
    .col-md-6
      .form-group
        %label Particiation Hours
        = f.number_field :participation_hours, class: 'form-control'
  .row
    .col-md-6
      %label Participation Date
      = f.date_field :participation_date, class: 'form-control'
    .col-md-6
      %label Team
      = f.select :team_id, options_for_select( @user.teams.map{ |t| [t.name, t.id]}.uniq, @sport&.team_id), {}, class: 'form-control'
.modal-footer
  = f.submit 'Save', class: 'btn btn-primary'

app/views/users/sports/_new.html.haml
.modal-dialog
  .modal-content
    .modal-header
      Add New Sports Event
    = form_for @sport, url: user_sports_path(@user), method: :post, remote: true do |f|
      = render partial: 'form', locals: {f: f}

app/views/users/sports/create.js.erb
$('#user-sports').html("<%= j(render partial: 'shared/sports/index') %>")

$('#modal').html('').modal('hide')

app/views/users/sports/edit.js.erb
$('#modal').html("<%= j(render partial: 'edit') %>").modal('show')

app/views/users/teams/_index.html.haml
- @teams.each do |team|
  .row
    .col-sm-3
      %img.img-rounded{:src => "https://dummyimage.com/60x60/666/ffffff&text=No+Image"}/
      .form-group
        %h4.review-block-name
          = team.name
      .form-group
        = link_to "Invite", new_team_invitation_path(team), remote: true
    .col-sm-9
      = render partial: 'shared/users/row', locals: {users: team.users, full_render: false}
  %hr/

app/views/users/teams/index.js.erb
$('#user-teams-container').html("<%= j(render partial: 'users/teams/index') %>")

app/views/users/update.js.erb
$('#user-personal-profile').html("<%= j(render partial: 'personal_profile') %>")
$('#user-edit').html('')